[server]
headless = true
runOnSave = true

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#2c3e50"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f5f5"
textColor = "#212529"
font = "sans serif"